services:
  backend: 
    container_name: ejercicio3-php
    build: ./php
    restart: always
    ports:
      - 8000:80
    volumes:
      - scripts:/var/www/html
  db:
    container_name: ejercicio3-backend
    build: ./bbdd
    restart: always
    ports:
      - 4000:3306
    volumes:
      - datos_bbdd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    container_name: ejercicio3-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: bbdd
volumes:
  scripts:
  datos_bbdd:
